config/routes.rb
Kaenko::Application.routes.draw do
  get "privatechat/index"
  resources :privatechat, :except => [ :index, :create, :new, :edit, :show, :update, :destroy ] do
    collection do
      get :start_chat_session
    end
  end

	post 'public/new_message'
  get "public/index"
  
  devise_for :admins, :constraints => {:subdomain => 'bo.development'}, 
  controllers: { sessions: "admins/sessions" , passwords: "admins/passwords" , registrations: "admins/registrations" }, 
  :path => "/"

  
  devise_for :users, :controllers => {:registrations => "registrations", :confirmations => "confirmations", :sessions => "sessions", :passwords=>"passwords", :unlocks=>"unlocks"}, :path => "", :path_names => { :sign_out => 'logout'}
  
  devise_scope :admin do
    get "/login" => "devise/sessions#new"
    match 'admins/change_password' => 'admins/registrations#edit', :via=>[:get]
  end
  
  devise_scope :user do
    match 'change_password' => 'registrations#change_password', :as=>"change_password", :via=>[:get]
    
    match 'profile/:username' => 'registrations#profile', :as=>"view_profile", :via=>[:get]
    
    match 'member/sign_up' => 'registrations#member', :user => { :roleable_type => 'member' }, :via=>[:get]
    match 'personal/sign_up' => 'registrations#new', :user => { :roleable_type => 'personal' }, :via=>[:get]
    match 'business/sign_up' => 'registrations#new', :user => { :roleable_type => 'business' }, :via=>[:get]
    match 'premium/request' => 'registrations#new', :user => { :roleable_type => 'premium' }, :via=>[:get]
    
    match 'member/sign_up' => 'registrations#create_member', :roleable_type => 'member' , :via=>[:post]
    match 'personal/sign_up' => 'registrations#create', :roleable_type => 'personal' , :via=>[:post]
    match 'business/sign_up' => 'registrations#create', :roleable_type => 'business' , :via=>[:post]
    match 'premium/request' => 'registrations#create', :roleable_type => 'premium' , :via=>[:post]
    match '/confirm/:confirmation_token' => "confirmations#show", :as => "user_confirm", :via=>[:get]
  end

  constraints subdomain: ["development",""] do
    match 'list_states' => 'homes#list_states', :as=>"list_states", :via=>["get"]
    match 'search_users' => 'homes#search_users', :as=>"search_users", :via=>["get"]
    get 'dashboard_overview' => 'homes#dashboard_overview'
    get 'dashboard_payment' => 'homes#dashboard_payment'
    get 'dashboard_history' => 'homes#dashboard_history'
    get 'groups' => 'homes#groups'
    get 'add_funds' => 'homes#add_funds'
    get 'withdraw' => 'homes#withdraw'
    get 'exchange' => 'homes#exchange'
    get 'sell_online' => 'homes#sell_online'    
    get 'referrals' => 'user_referrals#index'
    match 'account_setting' => 'accounts#index', :as=>"account_setting", :via=>["get"]
    match 'account_setup' => 'accounts#account_setup', :as=>"account_setup", :via=>["get"]
    match 'account_setting' => 'accounts#update', :as=>"update_setting", :via=>["put"]
    match 'update_security' => 'accounts#update_security', :as=>"update_security", :via=>["put"]
    match 'verify' => 'accounts#verify', :as=>"verify", :via=>["get"]
    match 'verified' => 'accounts#verified', :as=>"verified", :via=>["post"]
    get 'auth/:provider/callback' => 'homes#user_list'
    get 'auth/failure' => "homes#user_failure"
    get 'list_subcategory' => "businesses#list_subcategory" 
    resources :businesses do
      member do
        get 'edit_address'
        put 'update_address'
        get 'edit_business_detail'
        put 'update_business_detail'
        get 'edit_business_address_document'
        get 'edit_business_document'
        put 'update_field'
        get 'update_country'
        get 'businesss_update'
        get 'update_city_postal'
        get 'update_email'
        get 'update_phone'
        get 'update_address'
        get 'update_region'
        get 'update_name'
        get 'edit_business_contact'
        put 'update_contact'
        get 'update_desc'

      end
      collection do
        post 'verify_address_document'
        post 'upload_business_document'
        post 'update_image'

      end
    end
    resources :invites
    resources :kaenko_notifications do
      collection do
        get 'notification_check'
        get 'delete_notification'
        get 'unread_notification'
        get 'total_notification'

      end
    end
    resources :accounts do
      member do
        get 'edit_account_document'
        get 'edit_account_id_document'
        get 'edit_status'
        get :update_popup_time_zone
        get :privacy_settings
        get :email_notification
      end  
      collection do
        get :update_currency
        post :upload_account_document
        post :upload_account_id_document
        get :update_time_zone

      end
      resources :account_chats, only: [:new, :create, :destroy] do
        member do
          get :load_message
          get :load_search_msg
        end
      end
      resources :add_funds do
        collection do
          get :new_order
          post :process_new_card
          post :process_existing_card

        end
      end
      resources :withdraw_funds do
        collection do
          post :process_order

        end
      end
    end
    resources :premium_requests
    resources :messages do
      collection do
        get :to_user
        get :autocomplete_user_email
        get :total_messages
        get :archive_list
        get :unread_list
        get :total_messages
        get :popup_messages
        get :message_recent
        get :search_message
        get :show_archive
        get :unread_message

      end
      member do
        get :trash_show_message 
        post :reply
        post :trash
        post :archive
        get :search_within_message
        post :reply_archive
        get :archive_detail
        get :unread_detail
        post :export_conversation
        post :download_attachment
      end
    end
    root 'homes#index'
    resources :transactions do
      member do
        get 'accept'
        get 'reject'
        get 'cancel'
        get 'popup_i_withdraw'
        get 'popup_i_addfund'
        get 'popup_i_payment'
        get 'refund'
        get 'issue_refund'
        post 'create_issue_refund'
      end
      collection do
        post 'review_send_money'
        get 'send_money'
        get 'pending'
        post 'circle_transaction'
      end
      resources :disputes do
        member do
          get 'accept_solution'
          get 'modify_solution'
          post 'modify_dispute_refund'
          post 'accept_dispute_refund'
        end
      end
    end
    resources :circles
    resources :user_referrals
    resources :online_users, only: [:index]
    resources :request_payments do
      member do
        get :pay_request
        get :cancel_request
      end
    end
    resources :invoices do
      member  do 
        get 'pay_invoice_payment'
        get 'cancel_request'
      end
    end
    resources :account_payment_settings , only: [:index]
    resources :banks do
      member do
        get :confirm_delete
        post :confirm_delete
        get :make_primary
      end
    end
    resources :cards do
      member do
        get :confirm_delete
        post :confirm_delete
        get :make_primary
      end
    end
    resources :users do
    	member do
    		get 'social'
        get 'edit_secret'
        put 'update_secret'
        get 'edit_address'
        put 'update_address'
        get 'edit_contact'
        put 'update_contact'
        get 'suspend_account'
        get 'edit_personal_address'
        put 'update_personal_address'
        get 'edit_address_document'
        get 'edit_subuser'
        put 'update_subuser'
        get 'edit_security_pin'
        put 'update_security_pin'
        get 'update_email'
        get 'update_country'
        get 'update_city_postal'
        get 'update_user_dob'
        get 'update_user_gender'
        get 'edit_permission'
        get 'update_permission'
        get 'edit_personal_subuser'
        get 'update_phone'
        get 'update_first_name'
        get 'update_last_name'
        get 'update_job_title'
        post 'upload_subuser_image'
        put 'update_secret_ques'
        put 'update_secret_ans'
        put 'update_secret_pin'
        put 'update_pay_out_over'
        get 'ask_security_pin'
        get 'check_pin'
        get 'social_message'
        get 'update_about_me'
        post 'create_social_message'

    	end
    	collection do
        get 'edit'
    		get 'advance_search'
        post 'update_image'
        get 'update_online_status'
        post 'verify_address_document'
        put 'update_language'
        post 'autocomplete_user'
        get 'search_connection'

    	end
    end
    resources :connections do
      collection do
        get 'pending_connection'
      end
      member do
        get 'approve_reject'
      end
    end
    get 'update_server' => 'homes#update_server'
    resources :posts do
      member do
        get 'make_private'
        get 'make_public'
      end
      resources :comments
    end
    resources :account_currencies do
      collection do
        get 'show_currency'
      end
      member do
        get 'remove_currency'
      end

    end
    resources :business_websites
    resources :payments do
      collection do
        get :expected_pay_outs
      end
    end
    resources :sell_onlines do
      collection do
        get 'dispute_glossary'
        get 'customer_glossary'
        get 'review_glossary'
        get 'seller'
        get 'tools'
      end
    end

    
  end

  constraints(:subdomain => 'bo.development') do
    scope module: :admins do
      match 'settings' => 'kaenko_settings#index', :as=>"kaenko_setting", :via=>["get"]
      match 'settings/edit' => 'kaenko_settings#edit', :as=>"edit_kaenko_setting", :via=>["get"]
      match 'settings' => 'kaenko_settings#update', :as=>"update_kaenko_setting", :via=>["put","patch"]

app/controllers/admins/businesses_controller.rb
# encoding: utf-8
class Admins::BusinessesController < ApplicationController
	skip_before_filter :authenticate_user!
  before_filter :authenticate_admin!
  before_filter :load_business
  layout "admin"

  def edit
  end

  def update
  	if @business.update_attributes(business_params)
  		redirect_to users_path
  	else
  		render :edit
  	end
  end

  private

  def business_params
  	params.require(:business).permit(:country_of_incorporation, 
                                :organization_name, :organization_url, :legal_form,
                                :registration_number, :date_of_incorporation, :industry, 
                                :country, :state, :address, :city, :postal_code, :admin_id
                                )
  end

  def load_business
  	@business = Business.find(params[:id])
  end
end

app/controllers/businesses_controller.rb
# encoding: utf-8
class BusinessesController < ApplicationController

  def edit_address
    @business = business
  end

  def update_address
    @business = business
    @business.update_attributes(business_params)
  end
  
  def edit
    if params[:id].to_s == current_user.account.roleable_id.to_s and current_user.account_admin
      @business = business
    else
      flash[:alert] = "You are not authorized to update other's Organization"
      redirect_to dashboard_url
    end
  end

  def edit_business_contact
     @business = business
  end
  
  def update_contact
    @business = business
    @business.update_attributes(business_params)
  end

  def list_subcategory
    @category = Category.find_by_id(params[:category_id])
    @sub_categories = @category.children if @category
    render :json => @sub_categories 
  end
  
  def update
    if params[:id].to_s == current_user.account.roleable_id.to_s and current_user.account_admin
      @business = business
      @business.update_attributes(business_params)
      flash[:notice] = "Organization Details successfully updated"
      redirect_to dashboard_url
    else
      flash[:alert] = "You are not authorized to update other's Organization"
      redirect_to dashboard_url
    end
  end

  def edit_business_address_document

  end
  def verify_address_document
    @business = business
    @business.address_document = params[:address_document]
    if @business.save
      @business.update_column(:address_verified, true)
      render :text => "Your Registered Address status is now Verified."
    else
      head :no_content, :status => :bad_request
    end
  end
  def edit_business_document

  end
  def upload_business_document
    @business = business
    @business.business_document = params[:business_document]
    if @business.save
      @business.update_column(:business_verified, true)
      render :text => "Your Business status is now Verified."
    else
      head :no_content, :status => :bad_request
    end
  end

  def update_field
    @business = business
    if business.update_attributes(business_params)
      render :text => "success"
    else
      head :no_content, :status => :bad_request
    end
    
  end

 
 
  def update_email
    @business = business
    @error = ""
    if !@business.update_attributes(business_params)
      @error = @business.errors.full_messages
    end

  end
  def update_phone
    @business = business
    @error = ""
    if !@business.update_attributes(business_params)
      @error = @business.errors.full_messages
    end

  end
  
  def update_name
    @business = business
    @error = ""
    if !@business.update_attributes(business_params)
      @error = @business.errors.full_messages
    end
  end

  def update_desc
    @business = business
    @error = ""
    if !@business.update_attributes(business_params)
      @error = @business.errors.full_messages
    end
  end
  
  def update_image
		@business = business
		@business.image = params[:business_pic]
	
		if @business.save
			render :json=>{:circle=>@business.image_url(:circle), :profile=>@business.image_url(:profile)}, layout: false
		else
			render :json =>{ :errors => @business.errors.full_messages.join("") }, :status => 422, :layout => false
		end
	end

  
  private

  def business_params
    params.require(:business).permit(:country_of_incorporation, :organization_name, 
                                      :organization_url, :legal_form, :registration_number, 
                                      :date_of_incorporation, :category_id, :sub_category_id, :country, :state, 
                                      :address, :city, :postal_code, :phone,  :admin_id, :email, :region, :description
                                    )
  end  

  def business
    current_user.account.roleable
  end
end

app/helpers/admins/businesses_helper.rb
module Admins::BusinessesHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
	def edit_field
		
	end
end

app/views/businesses/_address_form.html.erb
 <a href="javascript:void(0);" class="close-slide"  id="close-address-change-panel"><i class="fa fa-times"></i></a>
<ul>
  <li><h5>Edit Address</h5></li>    
  <li id = "business_address">
  <%= form_for(@business, url: update_address_business_path(@business), remote: true, :html => { :method => :put, id: "adding-card-form" }) do |f| %>  
    <div id="business_address_msg">
    </div>
    <div>
      <span>
        <label>Address:</label>
          <p>
          <%= f.text_field :address, step:4, max:30, size:30 %>
          </p>
      </span>
      <span>
        <label>City:</label>
        <p>
          <%= f.text_field :city %>
        </p>
      </span>
    </div>
    <div>
      <span>
        <label>ZIP/Postal:</label>
        <p>
          <%= f.text_field :postal_code, step:4, max:6, size:6, placeholder: "ZIP / Postal Code"   %>
        </p>
      </span>
      <span>
        <label>Region:</label>
          <p>
            <%= f.text_field :region,  placeholder: "Region / District"   %>
          </p>
      </span>
      <span>
        <label>Country:</label>

          <p>
           <!--  <select id="country-select-cc" class="ES-cc pd40">
              <option class="ES-cc">Spain</option>
              <option class="DE-cc">Germany</option>
              <option class="ZA-cc">Zimbabwe</option>
              <option class="GB-cc">United Kingdom</option>
            </select> -->
            <%= f.select :country, @kaenko_countries  %>
          </p>
      </span>
    </div>
    <div>
      <span>
        <a href="javascript:void(0);" id="update-address-btn" class="btn btn-success addcard-btn" ><i class="fa fa-repeat"></i>Update Address</a>
      </span>
    </div>
  <% end %>
  </li>
</ul>
<%= javascript_tag do %>
  $(function() {
    $("#close-address-change-panel").click(function(){
      $("#address-change-panel").addClass("in-out");
    });
    $("#update-address-btn").click(function() {
      $("#adding-card-form").submit();
    });
  });
<% end %>
  

app/views/businesses/_business_address.html.erb
<span><strong>Address:</strong><%= business_account.address %></span>
<span><strong>City &amp; Postal:</strong><%= business_account.city %>, <%= business_account.postal_code%></span>
<span><strong>Region:</strong><%= business_account.region %> </span>
<span><strong>Country:</strong> <%= country_name( business_account.country) %></span>

app/views/businesses/_business_address_document_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title">Verify Address</h4>
    </div>
      <div class="modal-body">
          <p style="display:none;" class="alert alert-warning" id="document_error"></p>
          <p style="display:none;" class="alert alert-success"></p>
          <div class="form-group">
            <div class="span3 offset1"><label>Address Document:<label></div>
            <div>
                <%= file_field_tag :address_document, id: "address_document" ,    class: "form-control input-sm" %>
            </div>
          </div>
          <br>
          <div class="row-fluid">
            <div class="span3 offset1">&nbsp;</div>
            <div class="span8"><%= submit_tag "Submit", type: "button", id: "doc_button" , :class=>"btn btn-primary" %></div>
          </div>
      </div>
    
  </div>
</div>
<%= javascript_tag do %>
  $(function() {
   
    $("#doc_button").on("click", function() {
      //$(this).closest('form').submit();
      var form_data = new FormData(); // Creating object of FormData class
        file_content = $("#address_document")[0].files[0]
        form_data.append("address_document", file_content);
        $.ajax({
          url: "<%= verify_address_document_businesses_path %>",
          type: "POST",
          processData: false,
          contentType: false,
          data: form_data,
          success: function(response) {
             $("#address_status").text(response).removeClass("alert alert-warning fade in").addClass("alert alert-success fade in");
             $("#edit_business_addr_btn").remove();
             $('#modal-window').modal('toggle');
          },
          error: function(response) {
            $("#document_error").html('Your Registered Address status is <strong>Not Verified</strong>');
          }
        });
    });
    
  });
<% end %>

app/views/businesses/_business_contact.html.erb
<span><strong>Website</strong>
  <%#= business_account.business_websites.where("is_primary=?", true).first.try(:website_url)%> 
  <%= business_account.organization_url %>
</span>
<span><strong>Email:</strong><%= business_account.email %> </span>
<span><strong>Phone Number:</strong><%= business_account.phone %></span>

app/views/businesses/edit_address.js.erb
$("#address-change-panel").html("<%= escape_javascript(render 'address_form') %>");
$(".ajax-loading").hide();

app/views/businesses/edit_business_address_document.js.erb
$("#modal-window").html("<%= escape_javascript(render 'business_address_document_form') %>");
$(".ajax-loading").hide();

app/views/businesses/edit_business_document.js.erb
$("#modal-window").html("<%= escape_javascript(render 'business_document_form') %>");
$(".ajax-loading").hide();

app/views/businesses/update_address.js.erb
<%if @business.errors.any? %>
	$("#business_address_msg").html("<%= @business.errors.full_messages.join(",") %>")
<% else %>
	$("#business_address_msg").html("Address Updated.")
	$("#busi-prof-1").html("<%= j(render :partial => 'business_address',
	 locals: {:business_account => @business}) %>")
<% end %>

app/views/businesses/update_city_postal.js.erb
<%if !@error.present? %>
	$("#city_postal_text").html("<%= @business.city %>(<%= @business.postal_code%>)").show()
<% else %>
	$("#city_postal_text").html("<%= @error %>").show()
<% end %>
 $("#city_postal_text").show();
 $("#change_city_postal").show();
 $("#city_postal").hide();

app/views/businesses/update_contact.js.erb
<%if @business.errors.any? %>
	$("#business_contact_msg").html("<%= @business.errors.full_messages.join(",") %>")
<% else %>
	$("#business_contact_msg").html("Contact Updated.")
	$("#busi-prof-2").html("<%= j(render :partial => 'business_contact',
	 locals: {:business_account => @business}) %>")
<% end %>

app/views/businesses/update_desc.js.erb
<%if !@error.present? %>
  $("#business_desc_text").html("<%= @business.description %>").show()
<% else %>
  $("#business_desc").html("<%= @error %>").show()
<% end %>
$("#edit_business_desc").hide();
$("#change_business_desc").show();

app/views/businesses/update_name.js.erb
<%if !@error.present? %>
	$("#business_name_text").html("<%= @business.organization_name %>").show()
<% else %>
	$("#business_name_text").html("<%= @error %>").show()
<% end %>
$("#edit_business_name").hide();
$("#change_business_name").show();

app/views/businesses/update_region.js.erb
<%if !@error.present? %>
	$("#business_region_text").html("<%= @business.region %>").show()
<% else %>
	$("#business_region_text").html("<%= @error %>").show()
<% end %>
$("#edit_business_region").hide();
$("#change_business_region").show();