config/routes.rb
Kaenko::Application.routes.draw do
  get "privatechat/index"
  resources :privatechat, :except => [ :index, :create, :new, :edit, :show, :update, :destroy ] do
    collection do
      get :start_chat_session
    end
  end

	post 'public/new_message'
  get "public/index"
  
  devise_for :admins, :constraints => {:subdomain => 'bo.development'}, 
  controllers: { sessions: "admins/sessions" , passwords: "admins/passwords" , registrations: "admins/registrations" }, 
  :path => "/"

  
  devise_for :users, :controllers => {:registrations => "registrations", :confirmations => "confirmations", :sessions => "sessions", :passwords=>"passwords", :unlocks=>"unlocks"}, :path => "", :path_names => { :sign_out => 'logout'}
  
  devise_scope :admin do
    get "/login" => "devise/sessions#new"
    match 'admins/change_password' => 'admins/registrations#edit', :via=>[:get]
  end
  
  devise_scope :user do
    match 'change_password' => 'registrations#change_password', :as=>"change_password", :via=>[:get]
    
    match 'profile/:username' => 'registrations#profile', :as=>"view_profile", :via=>[:get]
    
    match 'member/sign_up' => 'registrations#member', :user => { :roleable_type => 'member' }, :via=>[:get]
    match 'personal/sign_up' => 'registrations#new', :user => { :roleable_type => 'personal' }, :via=>[:get]
    match 'business/sign_up' => 'registrations#new', :user => { :roleable_type => 'business' }, :via=>[:get]
    match 'premium/request' => 'registrations#new', :user => { :roleable_type => 'premium' }, :via=>[:get]
    
    match 'member/sign_up' => 'registrations#create_member', :roleable_type => 'member' , :via=>[:post]
    match 'personal/sign_up' => 'registrations#create', :roleable_type => 'personal' , :via=>[:post]
    match 'business/sign_up' => 'registrations#create', :roleable_type => 'business' , :via=>[:post]
    match 'premium/request' => 'registrations#create', :roleable_type => 'premium' , :via=>[:post]
    match '/confirm/:confirmation_token' => "confirmations#show", :as => "user_confirm", :via=>[:get]
  end

  constraints subdomain: ["development",""] do
    match 'list_states' => 'homes#list_states', :as=>"list_states", :via=>["get"]
    match 'search_users' => 'homes#search_users', :as=>"search_users", :via=>["get"]
    get 'dashboard_overview' => 'homes#dashboard_overview'
    get 'dashboard_payment' => 'homes#dashboard_payment'
    get 'dashboard_history' => 'homes#dashboard_history'
    get 'groups' => 'homes#groups'
    get 'add_funds' => 'homes#add_funds'
    get 'withdraw' => 'homes#withdraw'
    get 'exchange' => 'homes#exchange'
    get 'sell_online' => 'homes#sell_online'    
    get 'referrals' => 'user_referrals#index'
    match 'account_setting' => 'accounts#index', :as=>"account_setting", :via=>["get"]
    match 'account_setup' => 'accounts#account_setup', :as=>"account_setup", :via=>["get"]
    match 'account_setting' => 'accounts#update', :as=>"update_setting", :via=>["put"]
    match 'update_security' => 'accounts#update_security', :as=>"update_security", :via=>["put"]
    match 'verify' => 'accounts#verify', :as=>"verify", :via=>["get"]
    match 'verified' => 'accounts#verified', :as=>"verified", :via=>["post"]
    get 'auth/:provider/callback' => 'homes#user_list'
    get 'auth/failure' => "homes#user_failure"
    get 'list_subcategory' => "businesses#list_subcategory" 
    resources :businesses do
      member do
        get 'edit_address'
        put 'update_address'
        get 'edit_business_detail'
        put 'update_business_detail'
        get 'edit_business_address_document'
        get 'edit_business_document'
        put 'update_field'
        get 'update_country'
        get 'businesss_update'
        get 'update_city_postal'
        get 'update_email'
        get 'update_phone'
        get 'update_address'
        get 'update_region'
        get 'update_name'
        get 'edit_business_contact'
        put 'update_contact'
        get 'update_desc'

      end
      collection do
        post 'verify_address_document'
        post 'upload_business_document'
        post 'update_image'

      end
    end
    resources :invites
    resources :kaenko_notifications do
      collection do
        get 'notification_check'
        get 'delete_notification'
        get 'unread_notification'
        get 'total_notification'

      end
    end
    resources :accounts do
      member do
        get 'edit_account_document'
        get 'edit_account_id_document'
        get 'edit_status'
        get :update_popup_time_zone
        get :privacy_settings
        get :email_notification
      end  
      collection do
        get :update_currency
        post :upload_account_document
        post :upload_account_id_document
        get :update_time_zone

      end
      resources :account_chats, only: [:new, :create, :destroy] do
        member do
          get :load_message
          get :load_search_msg
        end
      end
      resources :add_funds do
        collection do
          get :new_order
          post :process_new_card
          post :process_existing_card

        end
      end
      resources :withdraw_funds do
        collection do
          post :process_order

        end
      end
    end
    resources :premium_requests
    resources :messages do
      collection do
        get :to_user
        get :autocomplete_user_email
        get :total_messages
        get :archive_list
        get :unread_list
        get :total_messages
        get :popup_messages
        get :message_recent
        get :search_message
        get :show_archive
        get :unread_message

      end
      member do
        get :trash_show_message 
        post :reply
        post :trash
        post :archive
        get :search_within_message
        post :reply_archive
        get :archive_detail
        get :unread_detail
        post :export_conversation
        post :download_attachment
      end
    end
    root 'homes#index'
    resources :transactions do
      member do
        get 'accept'
        get 'reject'
        get 'cancel'
        get 'popup_i_withdraw'
        get 'popup_i_addfund'
        get 'popup_i_payment'
        get 'refund'
        get 'issue_refund'
        post 'create_issue_refund'
      end
      collection do
        post 'review_send_money'
        get 'send_money'
        get 'pending'
        post 'circle_transaction'
      end
      resources :disputes do
        member do
          get 'accept_solution'
          get 'modify_solution'
          post 'modify_dispute_refund'
          post 'accept_dispute_refund'
        end
      end
    end
    resources :circles
    resources :user_referrals
    resources :online_users, only: [:index]
    resources :request_payments do
      member do
        get :pay_request
        get :cancel_request
      end
    end
    resources :invoices do
      member  do 
        get 'pay_invoice_payment'
        get 'cancel_request'
      end
    end
    resources :account_payment_settings , only: [:index]
    resources :banks do
      member do
        get :confirm_delete
        post :confirm_delete
        get :make_primary
      end
    end
    resources :cards do
      member do
        get :confirm_delete
        post :confirm_delete
        get :make_primary
      end
    end
    resources :users do
    	member do
    		get 'social'
        get 'edit_secret'
        put 'update_secret'
        get 'edit_address'
        put 'update_address'
        get 'edit_contact'
        put 'update_contact'
        get 'suspend_account'
        get 'edit_personal_address'
        put 'update_personal_address'
        get 'edit_address_document'
        get 'edit_subuser'
        put 'update_subuser'
        get 'edit_security_pin'
        put 'update_security_pin'
        get 'update_email'
        get 'update_country'
        get 'update_city_postal'
        get 'update_user_dob'
        get 'update_user_gender'
        get 'edit_permission'
        get 'update_permission'
        get 'edit_personal_subuser'
        get 'update_phone'
        get 'update_first_name'
        get 'update_last_name'
        get 'update_job_title'
        post 'upload_subuser_image'
        put 'update_secret_ques'
        put 'update_secret_ans'
        put 'update_secret_pin'
        put 'update_pay_out_over'
        get 'ask_security_pin'
        get 'check_pin'
        get 'social_message'
        get 'update_about_me'
        post 'create_social_message'

    	end
    	collection do
        get 'edit'
    		get 'advance_search'
        post 'update_image'
        get 'update_online_status'
        post 'verify_address_document'
        put 'update_language'
        post 'autocomplete_user'
        get 'search_connection'

    	end
    end
    resources :connections do
      collection do
        get 'pending_connection'
      end
      member do
        get 'approve_reject'
      end
    end
    get 'update_server' => 'homes#update_server'
    resources :posts do
      member do
        get 'make_private'
        get 'make_public'
      end
      resources :comments
    end
    resources :account_currencies do
      collection do
        get 'show_currency'
      end
      member do
        get 'remove_currency'
      end

    end
    resources :business_websites
    resources :payments do
      collection do
        get :expected_pay_outs
      end
    end
    resources :sell_onlines do
      collection do
        get 'dispute_glossary'
        get 'customer_glossary'
        get 'review_glossary'
        get 'seller'
        get 'tools'
      end
    end

    
  end

  constraints(:subdomain => 'bo.development') do
    scope module: :admins do
      match 'settings' => 'kaenko_settings#index', :as=>"kaenko_setting", :via=>["get"]
      match 'settings/edit' => 'kaenko_settings#edit', :as=>"edit_kaenko_setting", :via=>["get"]
      match 'settings' => 'kaenko_settings#update', :as=>"update_kaenko_setting", :via=>["put","patch"]

app/models/user_referral.rb
# encoding: utf-8
class UserReferral < ActiveRecord::Base
	#================
 	#  = Validations =
 	#================
	validates :email , presence: true, uniqueness: true

	#  ================
  #  = Associations =
  #  ================
	belongs_to :user

	#  ================
  #  = callbacks =
  #  ================

  before_save :check_existing_user

  def check_existing_user
  	user = User.where("email = ?", self.email)
  	user.size > 0 ? errors.add(:email, "Email is already registered, Please add another user email."): ""
  end

end

app/controllers/user_referrals_controller.rb
# encoding: utf-8
class UserReferralsController < ApplicationController
	def index
    @current_top_menu = "referrals"
    @referrals = current_user.user_referrals
    @total_earnings = current_user.user_referrals.sum(:current_earnings)
  end
  
	def new
    @current_top_menu = "referrals"
		@user_referral = UserReferral.new
	end
	
	def edit;end
	
	def create
		@user_referral = current_user.user_referrals.create(referral_params)
		if @user_referral.save
			UserMailer.send_referral(current_user, @user_referral.email).deliver
			respond_to do |format|
      	format.json { render json: @user_referral, status: :created }
      	format.js {
      		@referrals = current_user.user_referrals
      	}
      end
		else
			respond_to do |format|
        format.json { render json: @user_referral, status: :created }
        format.js{
        	@user_referral
        }
      end
		end
	end
	
	private
	
	def referral_params
		params.require(:user_referral).permit(:email)
	end
	
	
	
end

app/helpers/user_referrals_helper.rb
module UserReferralsHelper
end

app/views/user_referrals/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title">Referral User</h4>
    </div>
    <%= simple_form_for(@user_referral, remote: true, :html => { :method => :post }) do |f| %>
      <div class="modal-body">
          <p style="display:none;" class="alert alert-error"></p>
          <p style="display:none;" class="alert alert-success"></p>
          <div class="form-group">
            <div class="span3 offset1"><%= f.label :email %></div>
            <div>
              <%= f.input :email, :label=>false, :input_html=>{:class=>"form-control"}, placeholder: "Email" %>
            </div>
          </div>
          <br>
          <div class="row-fluid">
            <div class="span3 offset1">&nbsp;</div>
            <div class="span8"><%= f.submit "Submit", :class=>"btn btn-primary" %></div>
          </div>
      </div>
    <% end %>
  </div>
</div>

app/views/user_referrals/_index.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 id="myModalLabel">Invited Users</h3>
</div>
<br>
<% if @invites.present? %>
  <% @invites.each do |invite| %>
  <div class="row-fluid">
    <% u = User.find_by_email(invite.email) %>
    <% if u.present? %>
      <div class="span8 offset1"><%=link_to invite.email, view_profile_path(u.username) %></div>
      <div class="span3">Joined</div>
    <% else %>
      <div class="span8 offset1"><%=invite.email%></div>
      <div class="span3">Pending</div>
    <% end %>
  </div>
  <% end %>
<% else %>
  <br>
  <p class="alert alert-error">No Invitees Sent.</p>
  <br>
<% end %>
<br>

app/views/user_referrals/_referrals.html.erb
 
  

<!-- DATA AREA TITLE -->
<section class="withdraw main-container container-fluid">
  <div class="row row-50-top">
<div class="col-lg-12">
      <div class="row">
        <form action="">
            <!-- CARD CONTENT -->
              <article class="card col-lg-3 col-md-6 col-sm-12"> 
                <div class="panel panel-default"> 
                  <div class="panel-heading balance-heading">
                    My Commissions<span class="label label-info">EUR (Primary)</span>
                  </div> 
                  <div class="panel-body "> 
                    <div class="xbig-text text-center"><span id="total-referral">350.00 EUR</span>

                    <br><a href="#" class="btn btn-lg btn-info btn-sm">Transfer to <b>My Balance</b></a>

                  </div>
                     
                  </div> 
                  </div> 
              </article>
          <!--END  CARD CONTENT -->   
          <!-- CARD CONTENT -->
          <article class="card col-lg-3 col-md-6 col-sm-12"> 
            <div class="panel panel-default"> 
                <div class="panel-heading balance-heading">
                  My Referrals
                </div> 
                <div class="panel-body">
                  <div class="xbig-text text-center"><span id="total-referral">89 Active</span>
                    <br><small>1314 Total Invited</small>
                  </div>
                </div>

            </div> 
          </article>
          <!--END CARD CONTENT -->
            <!-- CARD CONTENT -->
          <article class="card col-lg-3 col-md-6 col-sm-12"> 
            <div class="panel panel-default"> 
                <div class="panel-heading balance-heading">My Referral ID</div> 
                <div class="panel-body">
                  <div class="xbig-text text-center"><span id="total-referral">info@keanko.com</span>
                    <br><%= link_to "Invite Friends", new_user_referral_path , remote: true,class: "btn btn-lg btn-default btn-sm", :'data-toggle' => "modal" , :'data-target' => "#modal-window" %>
<a href="#" class="btn btn-lg btn-default btn-sm"><i class="fa fa-link"></i></a>
                  </div>
                </div>

            </div> 
          </article>
          <!--END CARD CONTENT -->
        </form>
        </div>
        <div class="row">
            <!-- CARD TABLE -->
          <article class="card card-table col-lg-9">
            <div class="panel panel-default">
                <div class="panel-heading panel-heading-without-i recent-heading">
                  
                    My Commisions <span class="label label-info">EUR (Primary)</span>
                  
                </div>
                <div class="panel-body table-responsive">
                  <table class="table table-hover">
                      <thead class="">
                        <tr>
                          <td>
                            Email
                          </td>
                         
                          <td>
                            Status
                          </td>
                          <td align="right">
                            Current Earnings
                          </td>
                            <td align="right">
                            Total Earned (3,214.12 EUR)
                          </td>
                          
                        </tr>
                      </thead>
                      <tbody id="referral-list">
                          <tr>
                            <td colspan="4">
                              No Referral Available.
                            </td>
                          </tr>
                      </tbody>
                  </table>
                </div>
              </div>
          </article>
            <!-- END CARD TABLE -->
        </div>
    </div>
  </div><!-- END row -->
</section>

app/views/user_referrals/_referrals_list.html.erb
<%if @referrals.size > 0 %>
  <% @referrals.each do |referral| %>
    <tr>
      <td>
        <%= referral.email %>
      </td>
      <td>
        <span class="label label-success"><%= referral.status %></span>
      </td>
      <td align="right">
        <%= number_with_precision(referral.current_earnings, precision:2 || 0) %> USD
      </td>
    </tr>
  <% end %>
<% else %>
  <tr>
    <td>
      No Referral Available.
    </td>
  </tr>
<% end %>

app/views/user_referrals/create.js.erb
<%if @user_referral.errors.present? %>
	$('#modal-window').modal('toggle');
	$(".alert-warning").html("<%= @user_referral.errors.full_messages.join("") %>")
  $(".alert-warning").show()
<% else %>
	$('#modal-window').modal('toggle');
	$(".alert-warning").hide();
	$("#total-referral").html("<%= @referrals.size %>")
	$("#referral-list").html("<%= escape_javascript(render 'referrals_list') %>");
<% end %>
$(".ajax-loading").hide()

app/views/user_referrals/index.html.erb
<%= render 'referrals' %>

app/views/user_referrals/index.js.erb
$("#ajax-container").html("<%= j(render 'referrals' ) %>")
$(function() {
  history.pushState(null, "", "<%= referrals_path %>")
  $(window).bind("popstate", function(){
    $.getScript(location.href)
  })
})
$('[rel^=popover]').popover('hide');
$(".ajax-loading").hide()

app/views/user_referrals/new.js.erb
$(".alert-warning").hide();
$("#modal-window").html("<%= escape_javascript(render 'form') %>");
$(".ajax-loading").hide()