config/routes.rb
Kaenko::Application.routes.draw do
  get "privatechat/index"
  resources :privatechat, :except => [ :index, :create, :new, :edit, :show, :update, :destroy ] do
    collection do
      get :start_chat_session
    end
  end

	post 'public/new_message'
  get "public/index"
  
  devise_for :admins, :constraints => {:subdomain => 'bo.development'}, 
  controllers: { sessions: "admins/sessions" , passwords: "admins/passwords" , registrations: "admins/registrations" }, 
  :path => "/"

  
  devise_for :users, :controllers => {:registrations => "registrations", :confirmations => "confirmations", :sessions => "sessions", :passwords=>"passwords", :unlocks=>"unlocks"}, :path => "", :path_names => { :sign_out => 'logout'}
  
  devise_scope :admin do
    get "/login" => "devise/sessions#new"
    match 'admins/change_password' => 'admins/registrations#edit', :via=>[:get]
  end
  
  devise_scope :user do
    match 'change_password' => 'registrations#change_password', :as=>"change_password", :via=>[:get]
    
    match 'profile/:username' => 'registrations#profile', :as=>"view_profile", :via=>[:get]
    
    match 'member/sign_up' => 'registrations#member', :user => { :roleable_type => 'member' }, :via=>[:get]
    match 'personal/sign_up' => 'registrations#new', :user => { :roleable_type => 'personal' }, :via=>[:get]
    match 'business/sign_up' => 'registrations#new', :user => { :roleable_type => 'business' }, :via=>[:get]
    match 'premium/request' => 'registrations#new', :user => { :roleable_type => 'premium' }, :via=>[:get]
    
    match 'member/sign_up' => 'registrations#create_member', :roleable_type => 'member' , :via=>[:post]
    match 'personal/sign_up' => 'registrations#create', :roleable_type => 'personal' , :via=>[:post]
    match 'business/sign_up' => 'registrations#create', :roleable_type => 'business' , :via=>[:post]
    match 'premium/request' => 'registrations#create', :roleable_type => 'premium' , :via=>[:post]
    match '/confirm/:confirmation_token' => "confirmations#show", :as => "user_confirm", :via=>[:get]
  end

  constraints subdomain: ["development",""] do
    match 'list_states' => 'homes#list_states', :as=>"list_states", :via=>["get"]
    match 'search_users' => 'homes#search_users', :as=>"search_users", :via=>["get"]
    get 'dashboard_overview' => 'homes#dashboard_overview'
    get 'dashboard_payment' => 'homes#dashboard_payment'
    get 'dashboard_history' => 'homes#dashboard_history'
    get 'groups' => 'homes#groups'
    get 'add_funds' => 'homes#add_funds'
    get 'withdraw' => 'homes#withdraw'
    get 'exchange' => 'homes#exchange'
    get 'sell_online' => 'homes#sell_online'    
    get 'referrals' => 'user_referrals#index'
    match 'account_setting' => 'accounts#index', :as=>"account_setting", :via=>["get"]
    match 'account_setup' => 'accounts#account_setup', :as=>"account_setup", :via=>["get"]
    match 'account_setting' => 'accounts#update', :as=>"update_setting", :via=>["put"]
    match 'update_security' => 'accounts#update_security', :as=>"update_security", :via=>["put"]
    match 'verify' => 'accounts#verify', :as=>"verify", :via=>["get"]
    match 'verified' => 'accounts#verified', :as=>"verified", :via=>["post"]
    get 'auth/:provider/callback' => 'homes#user_list'
    get 'auth/failure' => "homes#user_failure"
    get 'list_subcategory' => "businesses#list_subcategory" 
    resources :businesses do
      member do
        get 'edit_address'
        put 'update_address'
        get 'edit_business_detail'
        put 'update_business_detail'
        get 'edit_business_address_document'
        get 'edit_business_document'
        put 'update_field'
        get 'update_country'
        get 'businesss_update'
        get 'update_city_postal'
        get 'update_email'
        get 'update_phone'
        get 'update_address'
        get 'update_region'
        get 'update_name'
        get 'edit_business_contact'
        put 'update_contact'
        get 'update_desc'

      end
      collection do
        post 'verify_address_document'
        post 'upload_business_document'
        post 'update_image'

      end
    end
    resources :invites
    resources :kaenko_notifications do
      collection do
        get 'notification_check'
        get 'delete_notification'
        get 'unread_notification'
        get 'total_notification'

      end
    end
    resources :accounts do
      member do
        get 'edit_account_document'
        get 'edit_account_id_document'
        get 'edit_status'
        get :update_popup_time_zone
        get :privacy_settings
        get :email_notification
      end  
      collection do
        get :update_currency
        post :upload_account_document
        post :upload_account_id_document
        get :update_time_zone

      end
      resources :account_chats, only: [:new, :create, :destroy] do
        member do
          get :load_message
          get :load_search_msg
        end
      end
      resources :add_funds do
        collection do
          get :new_order
          post :process_new_card
          post :process_existing_card

        end
      end
      resources :withdraw_funds do
        collection do
          post :process_order

        end
      end
    end
    resources :premium_requests
    resources :messages do
      collection do
        get :to_user
        get :autocomplete_user_email
        get :total_messages
        get :archive_list
        get :unread_list
        get :total_messages
        get :popup_messages
        get :message_recent
        get :search_message
        get :show_archive
        get :unread_message

      end
      member do
        get :trash_show_message 
        post :reply
        post :trash
        post :archive
        get :search_within_message
        post :reply_archive
        get :archive_detail
        get :unread_detail
        post :export_conversation
        post :download_attachment
      end
    end
    root 'homes#index'
    resources :transactions do
      member do
        get 'accept'
        get 'reject'
        get 'cancel'
        get 'popup_i_withdraw'
        get 'popup_i_addfund'
        get 'popup_i_payment'
        get 'refund'
        get 'issue_refund'
        post 'create_issue_refund'
      end
      collection do
        post 'review_send_money'
        get 'send_money'
        get 'pending'
        post 'circle_transaction'
      end
      resources :disputes do
        member do
          get 'accept_solution'
          get 'modify_solution'
          post 'modify_dispute_refund'
          post 'accept_dispute_refund'
        end
      end
    end
    resources :circles
    resources :user_referrals
    resources :online_users, only: [:index]
    resources :request_payments do
      member do
        get :pay_request
        get :cancel_request
      end
    end
    resources :invoices do
      member  do 
        get 'pay_invoice_payment'
        get 'cancel_request'
      end
    end
    resources :account_payment_settings , only: [:index]
    resources :banks do
      member do
        get :confirm_delete
        post :confirm_delete
        get :make_primary
      end
    end
    resources :cards do
      member do
        get :confirm_delete
        post :confirm_delete
        get :make_primary
      end
    end
    resources :users do
    	member do
    		get 'social'
        get 'edit_secret'
        put 'update_secret'
        get 'edit_address'
        put 'update_address'
        get 'edit_contact'
        put 'update_contact'
        get 'suspend_account'
        get 'edit_personal_address'
        put 'update_personal_address'
        get 'edit_address_document'
        get 'edit_subuser'
        put 'update_subuser'
        get 'edit_security_pin'
        put 'update_security_pin'
        get 'update_email'
        get 'update_country'
        get 'update_city_postal'
        get 'update_user_dob'
        get 'update_user_gender'
        get 'edit_permission'
        get 'update_permission'
        get 'edit_personal_subuser'
        get 'update_phone'
        get 'update_first_name'
        get 'update_last_name'
        get 'update_job_title'
        post 'upload_subuser_image'
        put 'update_secret_ques'
        put 'update_secret_ans'
        put 'update_secret_pin'
        put 'update_pay_out_over'
        get 'ask_security_pin'
        get 'check_pin'
        get 'social_message'
        get 'update_about_me'
        post 'create_social_message'

    	end
    	collection do
        get 'edit'
    		get 'advance_search'
        post 'update_image'
        get 'update_online_status'
        post 'verify_address_document'
        put 'update_language'
        post 'autocomplete_user'
        get 'search_connection'

    	end
    end
    resources :connections do
      collection do
        get 'pending_connection'
      end
      member do
        get 'approve_reject'
      end
    end
    get 'update_server' => 'homes#update_server'
    resources :posts do
      member do
        get 'make_private'
        get 'make_public'
      end
      resources :comments
    end
    resources :account_currencies do
      collection do
        get 'show_currency'
      end
      member do
        get 'remove_currency'
      end

    end
    resources :business_websites
    resources :payments do
      collection do
        get :expected_pay_outs
      end
    end
    resources :sell_onlines do
      collection do
        get 'dispute_glossary'
        get 'customer_glossary'
        get 'review_glossary'
        get 'seller'
        get 'tools'
      end
    end

    
  end

  constraints(:subdomain => 'bo.development') do
    scope module: :admins do
      match 'settings' => 'kaenko_settings#index', :as=>"kaenko_setting", :via=>["get"]
      match 'settings/edit' => 'kaenko_settings#edit', :as=>"edit_kaenko_setting", :via=>["get"]
      match 'settings' => 'kaenko_settings#update', :as=>"update_kaenko_setting", :via=>["put","patch"]

app/controllers/admins/users_controller.rb
# encoding: utf-8
class Admins::UsersController < ApplicationController
  skip_before_filter :authenticate_user!
  before_filter :authenticate_admin!
  layout "admin"
  before_filter :load_user, except: [:index]
  before_filter "active_tab('Users')" 

  def index
    @accounts = Account.includes(:users)
  end
  
  def show
    @sub_users = User.where("account_id = ? and account_admin = ?", @user.account_id, false)
  end

  def active_inactive
    @user.update_column(:active, @user.active ? false : true)
  end

  def user_details
  end

  def edit  
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

private
  
  def load_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :username, :first_name, :middle_name, 
      :last_name, :gender, :date_of_birth, 
      :nationality, :country, :state, :address, 
      :city, :postal_code, :phone
      )
  end
  
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/users/_form.html.erb
<%= simple_form_for [@user], :html => { :class => 'form-horizontal' } do |f| %>
	<div class="well-formbox">  
		<% if @user.errors.any? %>
		<div id="errorExplanation">
			<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
			<ul>
			<% @user.errors.full_messages.each do |msg| %>
			  <li><%= msg %></li>
			<% end %>
			</ul>
		</div>
		<% end %>
		<div class="control-group">
			<label class="control-label"> First Name: </label>
			<div class="controls">
				<%= f.input :first_name,  :label=>false %>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label"> Middle Name: </label>
			<div class="controls">
				<%= f.input :middle_name,  :label=>false %>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label"> Last Name: </label>
			<div class="controls">
				<%= f.input :last_name,  :label=>false %>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label"> Gender: </label>
			<div class="controls">
				<%= f.input :gender, :as=>"select", :collection=>[["Male","male"],["Female","female"]], :prompt=>"Gender", label: false %>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label"> Date of Birth: </label>
			<div class="controls">
				<%= f.input :date_of_birth, :as => "string" , :label=>false , :readonly => true %>
			</div>
		</div>
		
		<div class="control-group">
			<label class="control-label"> Nationality: </label>
			<div class="controls">
				<%= f.input :nationality, :as=>"select", :collection=>@kaenko_countries, :prompt=>"Nationality", label: false %>
			</div>
		</div>

		<div class="control-group">
			<label class="control-label"> Country: </label>
			<div class="controls">
				<%= f.input :country, :as=>"select", :collection=>@kaenko_countries, :prompt=>"Country", label: false %>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label"> State: </label>
			<div class="controls">
				<%= f.input :state, :as=>"select", :collection=>[], :include_blank=>true, :prompt=>"State/Region/District", label: false %>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label"> City: </label>
			<div class="controls">
				<%= f.input :city, :placeholder=>"City", label: false %>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label"> Postal code: </label>
			<div class="controls">
				<%= f.input :postal_code, :placeholder=>"Postal Code", label: false %>
			</div>
		</div>		
		<div class="control-group">
			<label class="control-label"> Phone: </label>
			<div class="controls">
				<%= f.input :phone, :placeholder=>"Phone", label: false %>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label"> Address: </label>
			<div class="controls">
				<%= f.input :address, :as => "text", :placeholder=>"Address" , label: false, :input_html=>{style: "width:390px;height:50px;"} %>
			</div>
		</div>
		 
		<div class="clearfix form-actions">
			<div class="col-md-offset-3 col-md-9">
				<%= f.submit :class => 'btn btn-info' %>
				<%= link_to :Canel, users_path, :class => 'btn' %>
			 </div>
		</div>
	</div>
<% end %>
<% content_for :script do %>
	<script src="/assets/admins/jquery-ui-1.10.3.custom.min.js"></script>
	<script src="/assets/admins/date-time/bootstrap-datepicker.min.js"></script>
	<script>

		function get_state(cid,sid)
		{
		  $.ajax({
		    url: '<%= list_states_url %>',
		    type: 'get',
		    data: {
		      country_2_code: cid
		    },
		    success: function(response) {
		      $("#user_state").html('');
		      $.each(response, function() {
		        if (sid == this[0])
		          $("#user_state").append("<option value='" + this[0] + "' selected>" + this[1] + "</option>");
		        else
		          $("#user_state").append("<option value='" + this[0] + "'>" + this[1] + "</option>");
		      });
		      $("#user_state").show();
		    },
		    error: function(response) {
		      window.console.log(response);
		    }
		  });
		}
		$(function() {
		  $( "#user_date_of_birth" ).datepicker({
		    defaultDate: "+1D",
		    maxDate:'-1D',
		    dateFormat: 'yy-m-d'
		  });
		});
		

		$("#user_country").change(function() {
		  get_state($(this).val(),'')
		});

		<% if @user.country.present? %>
		  get_state('<%=@user.country%>','<%=@user.state%>')
		<% end %>

	</script>
<% end %>

app/views/admins/users/_subuser_details.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 id="myModalLabel">User Details</h3>
</div>
<div class="row-fluid">
  <div class="span3 offset2"><strong>Name</strong></div>
  <div class="span1">:</div>
  <div class="span6"><%= @user.name %></div>
</div>
<div class="row-fluid">
  <div class="span3 offset2"><strong>Gender</strong></div>
  <div class="span1">:</div>
  <div class="span6"><%= @user.gender %></div>
</div>
<div class="row-fluid">
  <div class="span3 offset2"><strong>DOB</strong></div>
  <div class="span1">:</div>
  <div class="span6"><%= @user.date_of_birth %></div>
</div>
<div class="row-fluid">
  <div class="span3 offset2"><strong>Nationality</strong></div>
  <div class="span1">:</div>
  <div class="span6"><%= @user.nation %></div>
</div>
<div class="row-fluid">
  <div class="span3 offset2"><strong>Language</strong></div>
  <div class="span1">:</div>
  <div class="span6"><%= @user.language %></div>
</div>
<div class="row-fluid">
  <div class="span3 offset2"><strong>Phone</strong></div>
  <div class="span1">:</div>
  <div class="span6"><%= @user.phone %></div>
</div>
<div class="row-fluid">
  <div class="span3 offset2"><strong>Address</strong></div>
  <div class="span1">:</div>
  <div class="span6"><%= @user.full_address %></div>
</div>
<div class="row-fluid">
	<div class="span3 offset2">&nbsp;</div>
  <div class="span1">&nbsp;</div>
  <div class="span6">&nbsp;</div>
</div>

app/views/admins/users/active_inactive.js.erb
$("#li<%=@user.id%>").html('<%= link_to @user.active ? "Inactive" : "Active", active_inactive_user_path(@user), remote: true %>')
<% if @user.active? %>
	$("#active_<%=@user.id%>").html("A")
<% else %>
	$("#active_<%=@user.id%>").html("<span title='Active' class='badge badge-info' id='active_<%=@user.id%><span>")
<% end %>

app/views/admins/users/edit.html.erb
<%= render 'form' %>

app/views/admins/users/index.html.erb
<div class="row-fluid">
  <h3 style="display:none;" class="header smaller lighter blue">jQuery dataTables</h3>
  <div class="table-header">
    Results for "Approved Users"
  </div>

  <table id="table_report" class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th class="center">
          <label>
            <input type="checkbox" />
            <span class="lbl"></span>
          </label>
        </th>
        <th>Email</th>
        <th>Name</th>
        <th class="hidden-480">Account Type</th>

        <th class="hidden-phone">
          <i class="icon-time hidden-phone"></i>
          Account Opened
        </th>
        
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @accounts.each do |account| %>
        <% user = account.users.first %>
        <tr>
          <td class="center">
            <label>
              <input type="checkbox" />
              <span class="lbl"></span>
            </label>
          </td>

          <td>
            <%=link_to user.email, user_path(user)%>
          </td>
          <td><%= user.name%></td>
          <td class="hidden-480"><%=account.roleable_type%></td>
          <td class="hidden-phone"><%=account.created_at%></td>
          <td>
              <%=(account.premium) ? '<span  class="badge badge-important" title="Premium">P</span>'.html_safe : '<span class="label label-warning"></span>'.html_safe %>
              <%=(account.approved) ? '<span  title="Approved"><img src= "/assets/Apply.ico" /></span>'.html_safe : '<span class="label label-warning"></span>'.html_safe %>
              <%=(account.verified) ? '<span  title="Verified" class="badge badge-warning">V</span>'.html_safe : '<span class="label label-warning"></span>'.html_safe %>
              
              <%=(user.active) ? "<span  title='Active' class='badge badge-info' id='active_#{user.id}'>A</span>".html_safe : "<span  id='active_#{user.id}' class='badge badge-info'></span>".html_safe %>
          </td>
          <td class="td-actions">

            <div class="inline position-relative">
              <button data-toggle="dropdown" class="btn btn-minier btn-primary dropdown-toggle">
                <i class="icon-cog icon-only bigger-110"></i>
              </button>

              <ul class="dropdown-menu dropdown-icon-only dropdown-light pull-right dropdown-caret dropdown-close">
                <% if account.roleable_type == "Business" %>
                  <li>
                    <%= link_to "Edit Business", edit_business_path(user.account.roleable) %>
                  </li>
                <% end %>
                <li id="li<%=user.id%>">
                  <%= link_to user.active ? "Inactive" : "Active", active_inactive_user_path(user), remote: true %>
                </li>
                
                <li>
                  <a data-placement="left" title="" data-rel="tooltip" class="tooltip-success" href="<%= edit_user_path(user) %>" data-original-title="Edit">
                    <span class="green">
                      <i class="icon-edit"></i>
                    </span>
                  </a>
                </li>

                <li>
                  <a data-placement="left" title="" data-rel="tooltip" class="tooltip-warning" href="#" data-original-title="Flag">
                    <span class="blue">
                      <i class="icon-flag"></i>
                    </span>
                  </a>
                </li>

                <li>
                  <a data-placement="left" title="" data-rel="tooltip" class="tooltip-error" href="#" data-original-title="Delete">
                    <span class="red">
                      <i class="icon-trash"></i>
                    </span>
                  </a>
                </li>
              </ul>
            </div>
          </td>
        </tr>

      <% end %>
      
    </tbody>
  </table>
</div>


<% content_for :script do %>
  <script src="/assets/admins/jquery-ui-1.10.3.custom.min.js"></script>
  <script src="/assets/admins/jquery.dataTables.min.js"></script>
  <script src="/assets/admins/jquery.dataTables.bootstrap.js"></script>
<% end %>

<% content_for :inlinescript do %>
  <script type="text/javascript">
    $(function() {
      var oTable1 = $('#table_report').dataTable( {
      "aoColumns": [
          { "bSortable": false },
          null, null,null, null, null,
        { "bSortable": false }
      ] } );
      
      
      $('table th input:checkbox').on('click' , function(){
        var that = this;
        $(this).closest('table').find('tr &gt; td:first-child input:checkbox')
        .each(function(){
          this.checked = that.checked;
          $(this).closest('tr').toggleClass('selected');
        });
          
      });
    
      $('[data-rel=tooltip]').tooltip();
    })
  </script>
<% end %>

app/views/admins/users/show.html.erb
<h3 style="display:none;" class="header smaller lighter blue">jQuery dataTables</h3>
<div class="table-header">
  Account Details
</div>
<div class="center">
  <div class="row-fluid">
    <div class="span3 offset2"><strong>Username</strong></div>
    <div class="span1">:</div>
    <div class="span6"><%=@user.username%></div>
  </div>
  <div class="row-fluid">
    <div class="span3 offset2"><strong>Email</strong></div>
    <div class="span1">:</div>
    <div class="span6"><%=@user.email%></div>
  </div>
  <div class="row-fluid">
    <div class="span3 offset2"><strong>Name</strong></div>
    <div class="span1">:</div>
    <div class="span6"><%=@user.name%></div>
  </div>
  <div class="row-fluid">
    <div class="span3 offset2"><strong>Account ID</strong></div>
    <div class="span1">:</div>
    <div class="span6"><%=@user.account.account_number%></div>
  </div>
  <div class="row-fluid">
    <div class="span3 offset2"><strong>Account Type</strong></div>
    <div class="span1">:</div>
    <div class="span6"><%=@user.account.roleable_type%> <%=(@user.account.premium) ? "(Premium)" : ""%></div>
  </div>
  <div class="row-fluid">
    <div class="span3 offset2"><strong>Gender</strong></div>
    <div class="span1">:</div>
    <div class="span6"><%=@user.gender%></div>
  </div>
  <div class="row-fluid">
    <div class="span3 offset2"><strong>Date Of Birth</strong></div>
    <div class="span1">:</div>
    <div class="span6"><%=@user.date_of_birth.strftime("%d-%m-%Y")%></div>
  </div>
  <div class="row-fluid">
    <div class="span3 offset2"><strong>Language</strong></div>
    <div class="span1">:</div>
    <div class="span6"><%=@user.language%></div>
  </div>
  <div class="row-fluid">
    <div class="span3 offset2"><strong>Nationality</strong></div>
    <div class="span1">:</div>
    <div class="span6"><%=@user.nation%></div>
  </div>
  <div class="row-fluid">
    <div class="span3 offset2"><strong>Address</strong></div>
    <div class="span1">:</div>
    <div class="span6"><%=@user.full_address%></div>
  </div>
  <div class="row-fluid">
    <div class="span3 offset2"><strong>Phone</strong></div>
    <div class="span1">:</div>
    <div class="span6"><%=@user.phone%></div>
  </div>
  <% if @user.account.roleable_type == "Business" %>
  <div class="row-fluid">
    <div class="span3 offset2"><strong>Representative Position</strong></div>
    <div class="span1">:</div>
    <div class="span6"><%=@user.representative_position%></div>
  </div>
  <% end %>
</div>

<% if @user.account.roleable_type == "Business" %>
<div class="table-header">
  Business Details
</div>
<div class="center">
  <div class="row-fluid">
    <div class="span3 offset2"><strong>Country of Incorporation</strong></div>
    <div class="span1">:</div>
    <div class="span6"><%=@user.account.roleable.incorporation_country%></div>
  </div>
  <div class="row-fluid">
    <div class="span3 offset2"><strong>Organization Name</strong></div>
    <div class="span1">:</div>
    <div class="span6"><%=@user.account.roleable.organization_name%></div>
  </div>
  <div class="row-fluid">
    <div class="span3 offset2"><strong>Organization URL</strong></div>
    <div class="span1">:</div>
    <div class="span6"><%=link_to @user.account.roleable.organization_url, @user.account.roleable.organization_url, :target=>"_blank"%></div>
  </div>
  <div class="row-fluid">
    <div class="span3 offset2"><strong>Legal Form</strong></div>
    <div class="span1">:</div>
    <div class="span6"><%=@user.account.roleable.legal_form%></div>
  </div>
  <div class="row-fluid">
    <div class="span3 offset2"><strong>Registration Number</strong></div>
    <div class="span1">:</div>
    <div class="span6"><%=@user.account.roleable.registration_number%></div>
  </div>
  <div class="row-fluid">
    <div class="span3 offset2"><strong>Date Of Incorporation</strong></div>
    <div class="span1">:</div>
    <div class="span6"><%=@user.account.roleable.date_of_incorporation.strftime("%d-%m-%Y")%></div>
  </div>
  <div class="row-fluid">
    <div class="span3 offset2"><strong>Industry</strong></div>
    <div class="span1">:</div>
    <div class="span6"><%=@user.account.roleable.industry%></div>
  </div>
  <div class="row-fluid">
    <div class="span3 offset2"><strong>Registered Address</strong></div>
    <div class="span1">:</div>
    <div class="span6"><%=@user.account.roleable.full_address%></div>
  </div>
</div>
<% end %>
<div class="table-header">
  Subusers
</div>
<div class="center">
  <div class="row-fluid">
    <%@sub_users.each do |sub_user| %>
      <table id="table_report" class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th>Email</th>
            <th>Name</th>
            <th>Gender</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%=link_to sub_user.email, user_details_user_path(sub_user), remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'%>
            </td>
            <td><%= sub_user.name%></td>
            <td><%= sub_user.gender %></td>
          </tr>  
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/admins/users/user_details.js.erb
$("#modal-window").html("<%= escape_javascript(render 'subuser_details') %>");