config/routes.rb
    match 'admins/change_password' => 'admins/registrations#edit', :via=>[:get]
  end
  
  devise_scope :user do
    match 'change_password' => 'registrations#change_password', :as=>"change_password", :via=>[:get]
    
    match 'profile/:username' => 'registrations#profile', :as=>"view_profile", :via=>[:get]
    
    match 'member/sign_up' => 'registrations#member', :user => { :roleable_type => 'member' }, :via=>[:get]
    match 'personal/sign_up' => 'registrations#new', :user => { :roleable_type => 'personal' }, :via=>[:get]
    match 'business/sign_up' => 'registrations#new', :user => { :roleable_type => 'business' }, :via=>[:get]
    match 'premium/request' => 'registrations#new', :user => { :roleable_type => 'premium' }, :via=>[:get]
    
    match 'member/sign_up' => 'registrations#create_member', :roleable_type => 'member' , :via=>[:post]
    match 'personal/sign_up' => 'registrations#create', :roleable_type => 'personal' , :via=>[:post]
    match 'business/sign_up' => 'registrations#create', :roleable_type => 'business' , :via=>[:post]
    match 'premium/request' => 'registrations#create', :roleable_type => 'premium' , :via=>[:post]
    match '/confirm/:confirmation_token' => "confirmations#show", :as => "user_confirm", :via=>[:get]
  end

  constraints subdomain: ["development",""] do
    match 'list_states' => 'homes#list_states', :as=>"list_states", :via=>["get"]
    match 'search_users' => 'homes#search_users', :as=>"search_users", :via=>["get"]
    get 'dashboard_overview' => 'homes#dashboard_overview'
    get 'dashboard_payment' => 'homes#dashboard_payment'
    get 'dashboard_history' => 'homes#dashboard_history'
    get 'groups' => 'homes#groups'
    get 'add_funds' => 'homes#add_funds'
    get 'withdraw' => 'homes#withdraw'
    get 'exchange' => 'homes#exchange'
    get 'sell_online' => 'homes#sell_online'    
    get 'referrals' => 'user_referrals#index'
    match 'account_setting' => 'accounts#index', :as=>"account_setting", :via=>["get"]
    match 'account_setup' => 'accounts#account_setup', :as=>"account_setup", :via=>["get"]
    match 'account_setting' => 'accounts#update', :as=>"update_setting", :via=>["put"]
    match 'update_security' => 'accounts#update_security', :as=>"update_security", :via=>["put"]
    match 'verify' => 'accounts#verify', :as=>"verify", :via=>["get"]
    match 'verified' => 'accounts#verified', :as=>"verified", :via=>["post"]
    get 'auth/:provider/callback' => 'homes#user_list'
    get 'auth/failure' => "homes#user_failure"
    get 'list_subcategory' => "businesses#list_subcategory" 
    resources :businesses do
      member do
        get 'edit_address'
        put 'update_address'
        get 'edit_business_detail'
        put 'update_business_detail'
        get 'edit_business_address_document'
        get 'edit_business_document'
        put 'update_field'
        get 'update_country'
        get 'businesss_update'
        get 'update_city_postal'
        get 'update_email'
        get 'update_phone'
        get 'update_address'
        get 'update_region'
        get 'update_name'
        get 'edit_business_contact'
        put 'update_contact'
        get 'update_desc'

      end
      collection do
        post 'verify_address_document'
        post 'upload_business_document'
        post 'update_image'

      end
    end
    resources :invites
    resources :kaenko_notifications do
      collection do
        get 'notification_check'
        get 'delete_notification'
        get 'unread_notification'
        get 'total_notification'

      end
    end
    resources :accounts do
      member do
        get 'edit_account_document'
        get 'edit_account_id_document'
        get 'edit_status'
        get :update_popup_time_zone
        get :privacy_settings
        get :email_notification
      end  
      collection do
        get :update_currency
        post :upload_account_document
        post :upload_account_id_document
        get :update_time_zone

      end
      resources :account_chats, only: [:new, :create, :destroy] do
        member do
          get :load_message
          get :load_search_msg
        end
      end
      resources :add_funds do
        collection do
          get :new_order
          post :process_new_card
          post :process_existing_card

        end
      end
      resources :withdraw_funds do
        collection do
          post :process_order

        end
      end
    end
    resources :premium_requests
    resources :messages do
      collection do
        get :to_user
        get :autocomplete_user_email
        get :total_messages
        get :archive_list
        get :unread_list
        get :total_messages
        get :popup_messages
        get :message_recent
        get :search_message
        get :show_archive
        get :unread_message

      end
      member do
        get :trash_show_message 
        post :reply
        post :trash
        post :archive
        get :search_within_message
        post :reply_archive
        get :archive_detail
        get :unread_detail
        post :export_conversation
        post :download_attachment
      end
    end
    root 'homes#index'
    resources :transactions do
      member do
        get 'accept'
        get 'reject'
        get 'cancel'
        get 'popup_i_withdraw'
        get 'popup_i_addfund'
        get 'popup_i_payment'
        get 'refund'
        get 'issue_refund'
        post 'create_issue_refund'
      end
      collection do
        post 'review_send_money'
        get 'send_money'
        get 'pending'
        post 'circle_transaction'
      end
      resources :disputes do
        member do
          get 'accept_solution'
          get 'modify_solution'
          post 'modify_dispute_refund'
          post 'accept_dispute_refund'
        end
      end
    end
    resources :circles
    resources :user_referrals
    resources :online_users, only: [:index]
    resources :request_payments do
      member do
        get :pay_request
        get :cancel_request
      end
    end
    resources :invoices do
      member  do 
        get 'pay_invoice_payment'
        get 'cancel_request'
      end
    end
    resources :account_payment_settings , only: [:index]
    resources :banks do
      member do
        get :confirm_delete
        post :confirm_delete
        get :make_primary
      end
    end
    resources :cards do
      member do
        get :confirm_delete
        post :confirm_delete
        get :make_primary
      end
    end
    resources :users do
    	member do
    		get 'social'
        get 'edit_secret'
        put 'update_secret'
        get 'edit_address'
        put 'update_address'
        get 'edit_contact'
        put 'update_contact'
        get 'suspend_account'
        get 'edit_personal_address'
        put 'update_personal_address'
        get 'edit_address_document'
        get 'edit_subuser'
        put 'update_subuser'
        get 'edit_security_pin'
        put 'update_security_pin'
        get 'update_email'
        get 'update_country'
        get 'update_city_postal'
        get 'update_user_dob'
        get 'update_user_gender'
        get 'edit_permission'
        get 'update_permission'
        get 'edit_personal_subuser'
        get 'update_phone'
        get 'update_first_name'
        get 'update_last_name'
        get 'update_job_title'
        post 'upload_subuser_image'
        put 'update_secret_ques'
        put 'update_secret_ans'
        put 'update_secret_pin'
        put 'update_pay_out_over'
        get 'ask_security_pin'
        get 'check_pin'
        get 'social_message'
        get 'update_about_me'
        post 'create_social_message'

    	end
    	collection do
        get 'edit'
    		get 'advance_search'
        post 'update_image'
        get 'update_online_status'
        post 'verify_address_document'
        put 'update_language'
        post 'autocomplete_user'
        get 'search_connection'

    	end
    end
    resources :connections do
      collection do
        get 'pending_connection'
      end
      member do
        get 'approve_reject'
      end
    end
    get 'update_server' => 'homes#update_server'
    resources :posts do
      member do
        get 'make_private'
        get 'make_public'
      end
      resources :comments
    end
    resources :account_currencies do
      collection do
        get 'show_currency'
      end
      member do
        get 'remove_currency'
      end

    end
    resources :business_websites
    resources :payments do
      collection do
        get :expected_pay_outs
      end
    end
    resources :sell_onlines do
      collection do
        get 'dispute_glossary'
        get 'customer_glossary'
        get 'review_glossary'
        get 'seller'
        get 'tools'
      end
    end

    
  end

  constraints(:subdomain => 'bo.development') do
    scope module: :admins do
      match 'settings' => 'kaenko_settings#index', :as=>"kaenko_setting", :via=>["get"]
      match 'settings/edit' => 'kaenko_settings#edit', :as=>"edit_kaenko_setting", :via=>["get"]
      match 'settings' => 'kaenko_settings#update', :as=>"update_kaenko_setting", :via=>["put","patch"]
      match 'list_states' => 'homes#list_states', :as=>"admin_list_states", :via=>["get"]
      
      resources :users do
        member do
          get 'active_inactive'  
          get 'user_details'
        end
      end
      resources :businesses 
      resources :premium_requests do
        member do
          get 'approve'
          get 'reject'
        end
      end
      resources :faqs
      resources :referrals
      resources :earnings
      resources :fees_redemptions
      resources :fees_uploads
      resources :fees_from_tos
      resources :fees_exchanges
      resources :orders
      resources :transactions
      resources :timelines
      resources :api_clients
      get '', to: 'homes#index'
    end
  end
    
  constraints :subdomain => 'api' do

app/controllers/admins/transactions_controller.rb
# encoding: utf-8
class Admins::TransactionsController < ApplicationController
	skip_before_filter :authenticate_user!
  before_filter :authenticate_admin!
  layout "admin"
  before_filter "active_tab('Transactions')"
  
  def index
  	if params[:from].present?
  		@transactions = Transaction.where("transaction_from = ?", params[:from]).order('created_at desc')
  	else
  		@transactions = Transaction.order('created_at desc')
  	end
  end
end

app/helpers/admins/transactions_helper.rb
module Admins::TransactionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_circle_transaction_confirmation.html.erb
<article class="card col-sm-12 col-md-12 col-lg-12 col-xs-12"> 
  <div class="panel panel-default"> 
    <div class="panel-heading">
      <i class="kk-user light"></i>Mass Payment
    </div> 
    <div class="panel-body">
			<div>
				 <%= @success_transaction.size > 0 ? "Successfull transaction of users :"+@success_transaction.join(',') :  @success_transaction.size %>
			</div>
			 <div>
			 	 <%= @rejected_transaction.size > 0 ? "Rejected transaction of users :"+@rejected_transaction.join(',') : "" %>
			 </div>
		</div>
	</div>
</article>

app/views/transactions/_issue_refund.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%=form_tag create_issue_refund_transaction_path(@trans.id) , id:"dispute_form", remote: true do %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title" id="myModalLabel">&nbsp;&nbsp;</h4>
      </div>
      <div class="modal-body">
         <div class="container-fluid">
          <div class="row" style="height:200px;">
            <div id="error_msg_refund"></div>
            <p><strong>Issue Refund for Transaction ID:#</strong><%= @trans.transaction_id %> </p>            
            <p><strong>Payment From: <%= @trans.user.name %>(Account ID:# <%= @trans.transaction_id %>)</strong></p>
            <p><strong>Total Paid: <%= number_with_precision(@trans.amount, precision: 2 || 0)%> <%= @trans.kaenko_currency.unit %></strong>
            <p> <strong>Refund Amount: </strong><%=text_field_tag :refund_amount, "" %> <%= @trans.kaenko_currency.unit %> (max. <%= number_with_precision(@trans.amount, precision:2 || 0) %> <%= @trans.kaenko_currency.unit %>)
            <p>Note: Refunds have a cost of EUR: 3 (or equivalent)</p>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button  class= "btn btn-danger" data-dismiss="modal">Cancel </button>
        <%= submit_tag :'Refund Now', class: "btn btn-primary", style: "height:31px;" %>
      </div>
    <% end %> 
   </div>
</div>
<script>
  $(function() {
    $("#request_partial_refund").click(function() {
        $("#txt_partial").removeAttr("disabled")
    });
    $("#request_full_refund").click(function(){
      // body...
       $("#txt_partial").prop("disabled", true)
    }) 

  });
  
</script>

app/views/transactions/_popup_i_addfund.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h4 class="modal-title" id="myModalLabel">&nbsp;&nbsp;</h4>
    </div>
    
    <div class="modal-body">
      <div id="error_msg_social"></div>
       <div class="container-fluid">
        <div class="row">
          <p>
            <%if @trans.present? %>
              <strong> Transaction ID: # <%=@trans.transaction_id%>  <%= @trans.status %></strong> <br>
              <strong>Add Funds From : </strong> <%= @trans.payment_method %><br>
              <strong>We must  Received :</strong> <%= number_with_precision(@trans.amount, precision:2 || 0) %> <%= @trans.kaenko_currency.unit %><br>
              <strong> Total to be Credited : </strong> <%= number_with_precision(@trans.amount, precision:2 || 0) %> <%= @trans.kaenko_currency.unit %><br>
              <strong> Paid By: </strong>
              <%if @trans.roleable_type == "Bank" %>
                <p><strong>Bank Info:</strong></p>
                <p><strong>Account Name : </strong><%= @trans.roleable.name %></p>
                <p><strong>IBAN:</strong> <%= @trans.roleable.account_number %></p>
                <p><strong>SWIFT/BIC* :</strong> DB34334</p>
                <p><strong>Country: </strong><%= country_name(@trans.roleable.country) %></p>
                <p><strong>Memo: </strong><%= @trans.transaction_id %> </p>

                You must send the funds from the Verified Bank Account.
              <% else %>
                <p><strong>Card Info:</strong></p>
                <p><strong>Card</strong>  : <%= @trans.roleable.card_type %></p>
                <p><strong>Card Number:</strong> <%= @trans.roleable.card_number %></p>
              <% end %>
            <% end %>
          </p>
        </div>
      </div>
    </div>
    <div class="modal-footer">
    </div>
   
  </div>
</div>

app/views/transactions/_popup_i_withdraw.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h4 class="modal-title" id="myModalLabel">&nbsp;&nbsp;</h4>
    </div>
    
    <div class="modal-body">
      <div id="error_msg_social"></div>
       <div class="container-fluid">
        <div class="row">
          <p>
          <%if @trans.present? %>
            <p>
              <strong> Transaction ID: # <%=@trans.transaction_id%>  COMPLETED</strong> 
            </p>
            <p>
              <strong>Withdrawl To : </strong> <%= @trans.payment_method
            </p>
            <p>
              <strong>Total Debited :</strong> <%=number_with_precision(@trans.amount, precision:2 || 0) %> <%= @trans.kaenko_currency.unit %>
            </p>
            <p>
              <strong> Sending : </strong> <%= number_with_precision(@trans.amount, precision:2 || 0) %> <%= @trans.kaenko_currency.unit %>
            </p>
            <p>
              <strong>Automati order? </strong> Yes
            </p>
            <p>
              <strong>Periodicity: Weekly(next 18 Jan 2014)</strong>
            </p>
            <p>
              <strong>Amount: 100% Total Balance Available(estimated in primary currency</strong>
            </p>
            <p>
              Ending after 8 months 
            </p>

             
            <% end %>
          
          </p>
        </div>
      </div>
    </div>
    <div class="modal-footer">
    </div>
   
  </div>
</div>

app/views/transactions/circle_transaction.js.erb
<%if @error.present? %>
	$("#error_msg").html("<%= @error %>").show();
<% else %>
 $("#ajax-container").html("<%= j(render 'circle_transaction_confirmation' ) %>")
<% end %>
$(".ajax-loading").hide();

app/views/transactions/create.js.erb
<%if @error.present? %>
	$("#error_msg").html("<%= @error %>").show();
<% else %>
 $("#ajax-container").html("<%= @notice %>")
<% end %>
$(".ajax-loading").hide();

app/views/transactions/create_issue_refund.js.erb
<%if @error.present? %>
  $("#error_msg_refund").html("<%= @error %>").css("color", "red")
<% else %>
  $("#issue_refund<%=@trans.id%>").html("<a href='javascript:void(0)'><span class='label label-warning'>Refunded</span></a>")
  $("#status_parent<%=@trans.id %>").html("<a href='javascript:void(0)'><span class='label label-warning'>Refunded</span></a>")
  $("#status_child<%=@trans.id %>").html("Refunded").removeClass("label-success").addClass("label-warning")
  $('#modal-window').modal('toggle');
<% end %>
$(".ajax-loading").hide();

app/views/transactions/index.html.erb
<h2>Transactions</h2>
<div>
<%if @transactions.size > 0 %>
  <div class="row-fluid" style="font-weight:bold;">
    <div class="span3">Transaction ID</div>
    <div class="span3">Transfer To</div>
    <div class="span3">Amount</div>
    <div class="span3">Status</div>
  </div>
	<% @transactions.each do |transaction| %>
    <div class="row-fluid">
			<div class="span3"><%= transaction.transaction_id %></div>
			<div class="span3"><%= transaction.transaction_to %></div>
			<div class="span3"><%= transaction.amount.to_f %> <%= transaction.kaenko_currency.unit %></div>
			<div class="span3"><%= transaction.status %> <%= link_to "Cancel", cancel_transaction_path(transaction) if transaction.status == "pending" %></div>
		</div>
		<% end %>
<% else %>		
  <div class="row-fluid" style="font-weight:bold;">
    <div class="span12">No Transactions available</div>
  </div>
<% end %>
</div>

app/views/transactions/pending.html.erb
<h2>Transactions Pending at your end</h2>
<div>
<%if @transactions.size > 0 %>
  <div class="row-fluid" style="font-weight:bold;">
    <div class="span3">Transaction ID</div>
    <div class="span3">Received From</div>
    <div class="span3">Amount</div>
    <div class="span3">Action</div>
  </div>
	<% @transactions.each do |transaction| %>
    <div class="row-fluid">
			<div class="span3"><%= transaction.transaction_id %></div>
			<div class="span3"><%= transaction.transaction_from %></div>
			<div class="span3"><%= transaction.amount.to_f %> <%= transaction.kaenko_currency.unit %></div>
			<div class="span3"><%= link_to "Accept", accept_transaction_path(transaction) %> | <%= link_to "Reject", reject_transaction_path(transaction) %></div>
		</div>
		<% end %>
<% else %>		
  <div class="row-fluid" style="font-weight:bold;">
    <div class="span12">No Transactions</div>
  </div>
<% end %>
</div>

app/views/transactions/popup_i_addfund.js.erb
$("#modal-window").html("<%= j(render 'popup_i_addfund') %>");
$(".ajax-loading").hide();

app/views/transactions/popup_i_payment.js.erb
$("#modal-window").html("<%= j(render 'popup_i_payment') %>");
$(".ajax-loading").hide();

app/views/transactions/refund.js.erb
$("#modal-window").html("<%= j(render 'dispute') %>");
$(".ajax-loading").hide();

app/views/transactions/review_send_money.js.erb
$(".ajax-loading").hide();
<% if @error.present? %>
	$("#send_money_msg").html("<%= @error %>").show();
<% else %>
	$("#ajax-container").html("<%= j(render 'review_send_money_common') %>")
	$(function() {
		history.pushState(null, "", "<%= review_send_money_transactions_path %>")
		$(window).bind("popstate", function(){
	    $.getScript(location.href)
	  })
	})
<% end %>

app/views/transactions/send_money1.html.erb
<h2>Send Money</h2>

<%= simple_form_for(@transaction, :url=>review_send_money_transactions_path) do |f| %>

  <div class="row-fluid">
    <div class="span4 offset1">
      <div><%= f.input :transaction_to, :required=>"required", :label=>"Email ID of Receiver" %></div>
      <div><%= f.input :kaenko_currency, :as=>"select", :collection=>KaenkoCurrency.all, :placeholder=>"Select", :required=>"required" %></div>
      <div><%= f.input :amount, :placeholder=>"Amount", :label=>"Amount", :required=>"required" %></div>
      <div><br><%= f.submit "Send" %><%=link_to "Cancel", dashboard_overview_path, :style=>"float:right"%></div>
    </div>
    <div class="span4 offset2">
      <h4>Account Balance</h4>
    <% @balances.each do |balance| %>
      <div class="row-fluid">
        <div class="span4"><%=balance.balance%></div>
        <div class="span4 offset2"><%=balance.kaenko_currency.unit%></div>
      </div>
    <% end %>
    </div>
  </div>
  
<% end %>


<script>
	$(function() {
  $("#user_tokens").tokenInput("/messages/to_user.json", {
  	propertyToSearch : "email",
    crossDomain: false,
    tokenLimit: 1,
    prePopulate: $("#user_tokens").data("load"),
    theme: "facebook"
  });
});
</script>